using HotelBookingSystem_Abp.EntityFrameworkCore;

namespace HotelBookingSystem_Abp;

public class HotelBookingSystem_AbpWebCollection : HotelBookingSystem_AbpEntityFrameworkCoreCollectionFixtureBase
{

}
