using HotelBookingSystem_Abp.EntityFrameworkCore;
using Xunit;

namespace HotelBookingSystem_Abp.EntityFrameworkCore;

public class HotelBookingSystem_AbpEntityFrameworkCoreCollectionFixtureBase : ICollectionFixture<HotelBookingSystem_AbpEntityFrameworkCoreFixture>
{

}
